### PR TITLE
More cleanups for dunfell support

### PR DESCRIPTION
**Pull request by bboozzoo**
Some cleanups after #28 landed

### CODE REVIEW

**Comment by bboozzoo** [comment]
@morphis can you take a look at this PR?

**Comment by bboozzoo** [comment]
@om26er @oberstet please this branch a try if you have some spare cycles.

**Comment by oberstet** [comment]
thanks for coming back to this!

fwiw, work on our side rgd snapd and yocto is mangaged by @om26er: we run our own fork for now https://github.com/crossbario/meta-snappy ...

**Review by zyga — APPROVED** [review]
With my very inexperienced yocto eye, I think this looks fine.
Nice work on making apparmor optional now.

**Review by morphis — APPROVED** [review]
LGTM, thanks a lot!

**Pull request merged**
