### PR TITLE
Enable Apparmor Confinement

### PR DESCRIPTION
**Pull request by om26er**
This adds snapd strict confinement for Linux 5.4, it includes

* linux-yocto
* linux-raspberrypi

Patches are stolen from https://forum.snapcraft.io/t/apparmor-kernel-patches-for-5-x-kernels/19955/3

Also deletes unused patches and updates snapd to 2.51.5

### CODE REVIEW

**Comment by om26er** [comment]
I think we should change the `snappy.cfg` to make SQUASHFS support statically into the kernel instead of loading it as a module.

Reason: If a yocto system wants to boot from SquashFS (CONFIG_SQUASHFS=y), that will break the snapd build because `kernel-module-squashfs` won't be found

**Comment by asimaarbi** [comment]
Is there an update to this, it would be really great to have confinement working

**Comment by om26er** [comment]
ping @bboozzoo, did you get a chance to look at this PR ? 

Ultimately I would like to help maintain this project. We have a bunch of other improvements that we'd like to contribute to this project.

**Comment by om26er** [comment]
ping @bboozzoo

**Comment by bboozzoo** [comment]
The repo has moved to https://github.com/snapcore/meta-snapd. Please file an issue there.

**Pull request closed without merging**
